import '@/styles/globals.css'
import Head from 'next/head'
import Link from 'next/link'
import { SWRConfig } from 'swr'
import type { AppProps } from 'next/app'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

async function fetcher(resource: RequestInfo | URL, init?: RequestInit) {
  const res = await fetch(resource, init)
  return await res.json()
}

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={inter.className}>
        <div className="min-h-screen">
          <SWRConfig value={{ fetcher }}>
            <Component {...pageProps} />
          </SWRConfig>
        </div>
        <footer className="bg-zinc-900 py-16 px-8 mt-12 flex justify-center gap-x-8">
          <Link className="text-gray-100 hover:text-gray-300 hover:underline" href="/">Home</Link>
          <Link className="text-gray-100 hover:text-gray-300 hover:underline" href="/catalog">Catalog</Link>
          <Link className="text-gray-100 hover:text-gray-300 hover:underline" href="/cart">Cart</Link>
        </footer>
      </div>
    </>
  )
}
